### ISSUE TITLE
How to compile? Makefile?

### ISSUE THREAD

**Issue by mkg20001** [MGraefe/RP-Soundboard#1]

**Comment by mkg20001** [comment]
@MGraefe ???

**Comment by MGraefe** [comment]
There is a project file for Visual Studio 2012. You'll need the Qt Plugin.
In case you don't want to compile from source, here is a binary for Windows:
http://mgraefe.de/rpsb/dl/rp_soundboard_1349.ts3_plugin

**Comment by mkg20001** [comment]
I´m using Linux
