### ISSUE TITLE
PTT stops broadcasting sound to other clients

### ISSUE THREAD

**Issue by Palden1710** [MGraefe/RP-Soundboard#10]
Hey, great sounboard, however I'm having an issue with PTT turning off broadcasting to other people if I start talking during the middle of a song. AKA, I start playing a song, I press my PTT key and whenever I release it, the song continues to play locally but not to other clients.

**Comment by mehmet3** [comment]
192 168 1 1

**Comment by MGraefe** [comment]
Should be fixed in newest beta.
