### ISSUE TITLE
[FEATURE] Add a pause/stop button hotkey 

### ISSUE THREAD

**Issue by M-Davies** [MGraefe/RP-Soundboard#100]
To save tabbing out of games, it would be useful to have a hotkey that will stop or pause the currently playing sound. I recognise we can simply assign a blank audio file to a hotkey and use that as a sudo "stop" button as a workaround but it would be useful to have some framework in place nonetheless

**Comment by MGraefe** [comment]
You can right-click the pause/stop button and set a hotkey for it.

**Comment by M-Davies** [comment]
> You can right-click the pause/stop button and set a hotkey for it.

Ah thanks. Apologies. It wasn't very obvious just looking at the application 🙂
