### ISSUE TITLE
Hotkeys don't work

### ISSUE THREAD

**Issue by daminkon** [MGraefe/RP-Soundboard#102]
Hey I just downloaded  this soundboard and I guess it isn't that big of a issue but it would be really nice to have, basically the hotkeys aren't working, I can bind them, they will show on the buttons but they don't work, but clicking on the buttons with M1 works, so idk where's the problem.
![image](https://user-images.githubusercontent.com/78938108/107709773-0e0d2900-6cc6-11eb-9772-1bf03cd301e1.png)

**Comment by MGraefe** [comment]
Could you check what kind of settings are set in the Hotkey Menu of Teamspeak itself? You'll find that in the regular Teamspeak settings.

**Comment by daminkon** [comment]
![image](https://user-images.githubusercontent.com/78938108/107856663-ef27a780-6e29-11eb-8720-0bc2f68c1236.png)
Only button set is my ptt button which is MOUSE4

**Comment by vaio2005** [comment]
you didn't disable the hotkeys in the "settings" tab of the soundboard, right?
