### ISSUE TITLE
Hotkeys Doesnt Work

### ISSUE THREAD

**Issue by EliteCobra** [MGraefe/RP-Soundboard#111]
Good Day,

So the problem i have is that my hotkeys arent working.. i have nothing bound in my ts hotkeys except for the RP soundboard which is on my numpad..

Under my RP Soundboard settings Disable Hotkeys is not ticked so i see no reason for the hotkeys not to work.. if i am in game or not the hotkeys doesn't register and play the sound however it registers when i assign the hotkey, so the problem isnt keyboard related... i have attempted reinstalling and reloading the soundboard via TS addons but it still does the same.

**Comment by EliteCobra** [comment]
![Screenshot 2023-01-15 165329](https://user-images.githubusercontent.com/21226855/212548384-695e45ca-870a-4ec3-bc27-45f114bae1cf.png)
![Screenshot 2023-01-15 165402](https://user-images.githubusercontent.com/21226855/212548386-39ea33d0-9905-452a-9e4d-b94518d7a885.png)

**Comment by MGraefe** [comment]
Sorry for the late reply. Does the problem still exist? Do any other TS3 hotkeys (outside of RP soundboard) work?
