### ISSUE TITLE
pls update to api version 26

### ISSUE THREAD

**Issue by DEtrees95** [MGraefe/RP-Soundboard#114]
i cant use this pls update the api to 26  yes i use today the new beta 3.6.0
[teamspeak error](https://i.ibb.co/R3LpQQB/rpsoundapi26.png)

**Comment by KiwontaTv** [comment]
Yea please update it #push

**Comment by spezialzt** [comment]
Confirm, an update to API version 26 would be much appreciated!

**Comment by unhappytroll** [comment]
I do third that

**Comment by Care-Less** [comment]
I'll fourth this as well

**Comment by Jhovannino** [comment]
We need an update!

**Comment by FlofNoiflo** [comment]
I'll sixth that!

**Comment by Born2BGod** [comment]
![image](https://github.com/MGraefe/RP-Soundboard/assets/36622437/3ba9e9ee-9075-4495-9c4e-9ebf324e352c)

Please update the API.

btw, Is any other plug-in still can be used?   seem like all my plug-in are in a trouble.

**Comment by gamebeast2k** [comment]
i thing the project is dead. (¬_¬ )

**Comment by MGraefe** [comment]
Done: https://github.com/MGraefe/RP-Soundboard/releases/tag/v1.4.2.1819

**Comment by kurtextrem** [comment]
Thank you!!
