### ISSUE TITLE
Internet radio stream or youtube stream

### ISSUE THREAD

**Issue by theoneandonlykinge** [MGraefe/RP-Soundboard#122]
maybe a cool feature would be if you can put a internet radio or youtube music stream in a button

**Comment by MGraefe** [comment]
I know many people want that, but it would be very hard to implement and also there is the whole copyright topic of essentially ripping an audio stream off a video or radio website.

There are other ways to implement a music bot or similar functionality and it's not in the scope for this soundboard.

**Comment by theoneandonlykinge** [comment]
i understand. thanks for all your hard and good work! great respect!
