### ISSUE TITLE
Hotkeys for volume change behave weirdly wrong

### ISSUE THREAD

**Issue by FlorianPanten** [MGraefe/RP-Soundboard#127]
- Bug Report -
I have bound "+" and "-" (Numpad) to both local and remote volume increase/decrease.
If setup like this, only the remote volume control works correctly.
When I press the hotkey for decreasing the local volume, it sets itself to 0 rather than decreasing itsself by 20%.
When I press the hotkey for increasing the local volume, it does sometimes work but very very unreliably. Most of the times nothing happens.

**Comment by FlorianPanten** [comment]
I just saw, this issue has already beeen resolved though there is no release with that fix yet

**Comment by FlorianPanten** [comment]
The issue has already been resolved in a commit though there is no release yet

**Comment by MGraefe** [comment]
Sorry, I forgot to actually build a new release. It's out now: https://github.com/MGraefe/RP-Soundboard/releases/tag/v1.4.5

**Comment by FlorianPanten** [comment]
Thanks. Btw I tried to build it with Github but it failed. I just forked it and pushed a change in the readme file so it triggers a build. The build process started but it failed

**Comment by MGraefe** [comment]
Weird, here it works. Any info on the specific error?

**Comment by FlorianPanten** [comment]
![image](https://github.com/MGraefe/RP-Soundboard/assets/93984246/4b572646-4441-4c00-839e-b22c8a4c52ac)
`Run cmake --build D:\a\RP-Soundboard\RP-Soundboard/build --config Release --target INSTALL
MSBuild version 17.8.5+b5265ef37 for .NET Framework

  1>Checking Build System
  running autogen file script
  fatal: No names found, cannot describe anything.
  Traceback (most recent call last):
    File "D:\a\RP-Soundboard\RP-Soundboard\version.py", line 76, in <module>
      sys.exit(main())
               ^^^^^^
    File "D:\a\RP-Soundboard\RP-Soundboard\version.py", line 19, in main
      versionStr = subprocess.check_output(['git', 'describe', '--tags']).decode().strip()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\subprocess.py", line 466, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\subprocess.py", line 571, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'D:\a\RP-Soundboard\RP-Soundboard\build\CMakeFiles\18d1e84573ed8a009[15](https://github.com/FlorianPanten/RP-Soundboard/actions/runs/7834485667/job/21377804170#step:5:16)998766f3ad0f4\autogenFiles.rule;D:\a\RP-Soundboard\RP-Soundboard\CMakeLists.txt' exited with code 1. [D:\a\RP-Soundboard\RP-Soundboard\build\autogenFiles.vcxproj]
Error: Process completed with exit code 1.`

**Comment by FlorianPanten** [comment]
Weird I just looked at the actions and I saw there was a prior build running that worked. I could have sworn that that wasnt there before ^^
![image](https://github.com/MGraefe/RP-Soundboard/assets/93984246/a661da63-4299-4025-9314-35e82780bd92)
And here to show that I really just edited the readme and nothing more.
![image](https://github.com/MGraefe/RP-Soundboard/assets/93984246/4ed07b97-63e2-4662-b6f3-8d1f87269f1b)
