### ISSUE TITLE
sounds overlap

### ISSUE THREAD

**Issue by SergiX44** [MGraefe/RP-Soundboard#13]
Like in the old ts3soundboard, it possible to add an option to permit the sounds overlap? (when you repeatedly press the same button, it will play the sound separately for each click causing an overlap, instead of stop and restart the sound)

**Comment by MGraefe** [comment]
I don't think that would be very practical - and it would require a lot of changes under the hood with possible performance drawbacks (decoding the file multiple times simultanously). Keeping your idea though, maybe as an optional feature.
