### ISSUE TITLE
Current plugin does not work for latest teamspeak version

### ISSUE THREAD

**Issue by Vig-4** [MGraefe/RP-Soundboard#131]
![image_2024-09-17_161138980](https://github.com/user-attachments/assets/f30e8192-bf6a-412c-b733-70d259a78dfb)
i apologize i wish i could use 3.6.0 but everytime i try to join a server i crash it would mean alot to me if you could update this plugin ive loved using it for wacky banter

**Comment by naxIO** [comment]
Hmm strange because im using it in 3.6.2 and it works just fine! Maybe update then?
