### ISSUE TITLE
Rename Buttons

### ISSUE THREAD

**Issue by penderes** [MGraefe/RP-Soundboard#17]
Hi Marius,

thanks for the great plug-in!

Is there any possibility that you'll include an option to rename certain buttons? I like to structure my soundfiles with a lot of underscores and dashes, which looks a bit strange on the board. It would be greatly appreciated if there was an option to rename buttons with a custom string.

Thanks in advance!

**Comment by MGraefe** [comment]
Will be in the next release :)

**Comment by WarWolfen** [comment]
Hi!

Thank you for this, and for the Plugin in general. It is MUCH easier to deal with than the other solution I was using before.

If you add the option to rename buttons, would you consider to also add options for text design?
Things like:
- Bold font
- Italic font
- Underlined font
- Text color
- Button Background color
?

In my previous solution, I used quite a big board for online Roleplay session mastering and I used colors to mark different sound types (like Music, radio-chatter-samples, environmental noise, intros and the like). If all colors basicly look the same, it is quite hard to find them (if you were concentrated on a game and the other players and look to the board in desperate need in a quick reaction to something that just happened in the game).

Thanks again!
