### ISSUE TITLE
Sound play issue

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [MGraefe/RP-Soundboard#2]
There's a weird issue, sometimes the file is played well, and sometimes it is compressed. I don't know if it is linked, but maybe a load issue, because it seems to happen when there's several TS3 clients connected in the same TS3 Client (doesn't seems to happen if there's other TS3 with nosingleinstance, only if there's several tabs in the same TS3 instance).

**Comment by MGraefe** [comment]
You are right, I didn't see it. Sorry for that :)
The info that this is happening when having multiple server connections is quite useful. This could be related to different channel codecs, especially when one channel is stereo (aka opus music) and the other (on the other server) is mono. Inserting mono-samples into a stream that is stereo would explain the doubled playback speed. Maybe my plugin gets confused about whether the output signal should be mono or stereo when switching server tabs. I will take a look next week.

Thanks you very much for your effort!

**Comment by ZatsuneNoMokou** [comment]
You're welcomed, and the 2 teamspeak3 are both in Opus Voice, quality 6, so I dunno if it's a codec issue

**Comment by MGraefe** [comment]
Actually the two servers you are connected to read samples from the file at the same time. That is causing the issue. I think this is an easy fix, give me a few minutes ;)

**Comment by ZatsuneNoMokou** [comment]
Well, I'll try it if you do it

**Comment by MGraefe** [comment]
Here is the new version: http://mgraefe.de/rpsb/dl/rp_soundboard_1419.ts3_plugin
Would be nice if you could test it before I release it to the public :)

**Comment by ZatsuneNoMokou** [comment]
Sure I'll do it then

**Comment by ZatsuneNoMokou** [comment]
It work well now, thanks
