### ISSUE TITLE
Remove Shortcut

### ISSUE THREAD

**Issue by WarWolfen** [MGraefe/RP-Soundboard#20]
Hi!

How can a keyboard shortcut be removed from a button? I could not find a way, so maybe it is not possible? I could not find a way through the ini file either.

**Comment by MGraefe** [comment]
You can delete shortcuts in the teamspeak hotkey configuration dialog: Extra -> Options -> Hotkeys
I think it's an error on teamspeaks side that pressing ESC in the hotkey config dialog does not remove the hotkey but sets ESC as a key.
