### ISSUE TITLE
Cannot unbind 

### ISSUE THREAD

**Issue by ProIOnut** [MGraefe/RP-Soundboard#23]
Once i bind a hotkey to a sound i cannot unbind.I tryed to go advanced options change the hotkey and press esc and nothing happen it remains the same hotkey whatever button i chose.Pls help me out. #20

**Comment by MGraefe** [comment]
You can delete shortcuts in the teamspeak hotkey configuration dialog: Extra -> Options -> Hotkeys
I think it's an error on teamspeaks side that pressing ESC in the hotkey config dialog does not remove the hotkey but sets ESC as a key.
