### ISSUE TITLE
Hotkey stuck

### ISSUE THREAD

**Issue by burnoutcomputer** [MGraefe/RP-Soundboard#27]
If you end up setting your hotkey to MOUSE BUTTON 1, you cannot change the hotkey, and there is no feature to remove the hotkey. Uninstalling the plugin does not clear any settings or preferences, and I cannot locate the local files to delete the data manually. Once the hotkey is set to MOUSE BUTTON 1, no other sound buttons will work.

**Comment by WarWolfen** [comment]
As this is a re-occuring issue and people do seem to overlook the solution, what if you would add a menu item to each button (caption "remove hotkey") that is actually leading to TeamSpeaks own settings dialog and the hotkey page?

**Comment by MGraefe** [comment]
Teamspeak dev told me this will be fixed in the next release of Teamspeak.
