### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [MGraefe/RP-Soundboard#3]
I saw on the TeamSpeak topic "`may port to Mac/Linux in the future.`" so, do you know if there's much work to do to make it work? I'm a Linux user too (currently Xubuntu 16.04 for information)

**Comment by MGraefe** [comment]
I can't promise anything but I will look into it.

**Comment by monstah** [comment]
any updates on that?

**Comment by MGraefe** [comment]
Would you like to test a bleeding edge build for 64-bit Linux and Teamspeak 3.1 beta? 
[librp_soundboard.so.zip](https://github.com/MGraefe/RP-Soundboard/files/631746/librp_soundboard.so.zip)

Teamspeak 3.1 beta: Change update channel in Options/Application and search for updates after that
You'll also need the ffmpeg library, on Ubuntu(-derivates) do: `sudo apt-get install ffmpeg`.
Place librp_soundboard.so in the plugins directory in your Teamspeak installation.

**Comment by monstah** [comment]
sorry, I forgot to mention that I am using MacOS,so it won't run or? ffmpeg should be installed already.

**Comment by Adam-Ant** [comment]
Hey, any news on another linux build? The linked one no longer works.

**Comment by olback** [comment]
Is this still in the works? Would love to test some early beta or something.

**Comment by gabixdev** [comment]
I'm going to port to linux... https://github.com/gabixdev/RP-Soundboard-Linux

**Comment by gabixdev** [comment]
Oh, there's an qmake file, but still i can be linux version maintainer :)

**Comment by MGraefe** [comment]
There is but it isn't maintained properly and I always had some issues with linux; namely I am unsure what to do about different versions of ffmpeg installed on the users system. I have a statically linked ffmpeg version for Windows...and I think that would be the best option for linux as well. Theres no easy way around it when you have to deploy a single binary on very different distros.

**Comment by MGraefe** [comment]
I will commit the ffmpeg build script for the windows binaries tomorrow evening. Not at home atm.

**Comment by schulzh** [comment]
@MGraefe Could you please provide a new binary for Linux?
I see you made the necessary changes, but I have no idea how to compile it myself...

**Comment by gabixdev** [comment]
get qt compatible with ts3 (5.6 currently?) and build it with qmake

**Comment by bertalanimre** [comment]
I'm a bit lost now in the tickets. @MGraefe , I woluntier for testing if that is required. :) Ubuntu 17,10 with ffmpeg version 3.3.4-2

**Comment by rescuetoaster** [comment]
Hello kind Sir!
Tried to load the plugin on:
Linux debian 8
ts 3.2.1
qt 5.6.1
ffmpeg 10:2.6.5-dmo1 (amd64)

produces error in options - plugins:
Plugin failed to load: Failed to open plugin.: -574872952 (minimum: 21, current: 22)

Please let me know if I can provide more details or things to try.
