### ISSUE TITLE
[Feature Request] Search bar. 

### ISSUE THREAD

**Issue by Gianluca194** [MGraefe/RP-Soundboard#35]
As I have over 200 buttons on my second screen (adding new ones all the time) finding the right sound for a joke to get accross correctly is sometimes a difficult task. So what I would like is a small search box to quickly find the sound I am looking for. Maybe by highlighting the button or something. 

Really LOVE this soundboard btw !! Amazing !!

**Comment by Gianluca194** [comment]
This was actually added !! COOL !! This soundboard is actually perfect now

**Comment by MGraefe** [comment]
Yep, took me a while, sorry :)
