### ISSUE TITLE
API Version is not Compatible

### ISSUE THREAD

**Issue by VladVidya** [MGraefe/RP-Soundboard#36]
Latest Teamspeak version (as of 4/12/17) does not work with the addon. 

The error given is:
"Plugin failed to load: Api version is not compatible: 20 (minimum: 21, current: 22)"

**Comment by MGraefe** [comment]
This simply is not correct - the plugin is API 21 for quite some time now and thus always worked with Teamspeak 3.1. Try deleting the plugin and reinstall it.
