### ISSUE TITLE
RP-Soundboard doesnt work for me!

### ISSUE THREAD

**Issue by martinamama** [MGraefe/RP-Soundboard#38]
First of all the soundboard is very good. It used to work perfect. But on one day i go to Configuration 2 and played a File there. Then i couldnt change to Configuration 1. I clicked on configuration 1 it changed on Interface but if i click any file / click on the button which says "No file" then it goes back to Configuration 2. If i play a file there i have to click it multiply times and then it starts to play. I searched my whole Computer for "soundboard" and deleted all files i could find. Then i reinstalled RP-Soundboard (i exported my old files), so i changed the size to 10x10 again. If i pull it to the edge of my Window to make it fullscreen and click on anything it immediatly changes back to small size (10x10 still is there but the window goes back to small). And the Configuration 2 Problem is still there. And i dont know how to solve it. I even reinstalled it maybe its a bug in teamspeak3 client for me but i dont know and wanted to ask you. Thanks anyways :)

**Comment by martinamama** [comment]
Oh and the window kinda blinks if i click on something and the window gets smaller again. It kinda feels like it restarts the gui thingie. I dont have any knowledge of this stuff xD

**Comment by MGraefe** [comment]
Try deleting the config file: C:\Users\<USERNAME>\AppData\Roaming\TS3Client\rp_soundboard.ini

**Comment by Flamefighter** [comment]
I have the same Problem i have tried to Delete it but it still Change from config 1 to config 2

**Comment by pvthomer8383** [comment]
Also can't play files from the soundboard anymore.... :-(

**Comment by martinamama** [comment]
@Flamefighter @pvthomer8383 I didnt try to delet it, the way i got it working again was by deinstalling teamspeak. Searching my explorer for rp soundboard and deletet all files that have something to do with rp soundboard. Then i installed teamspeak again, same with rp soundboard and it works now again :)
