### ISSUE TITLE
echo sounds while using teamspeak recorder

### ISSUE THREAD

**Issue by dekurizu** [MGraefe/RP-Soundboard#42]
When using built in teamspeak sound recorder, the sounds played in soundboard turn out echoed and distorted, yet they sound just fine live in-channel. Only the soundboard sounds are echoed, normal speech is just fine. Any way to preserve sound quality when recording?

**Comment by Deziel0495** [comment]
I have noticed this as well. One way around it is to enable the "mute on my client" checkbox.

**Comment by MGraefe** [comment]
This was an issue in Teamspeak itself and seems to be fixed in the recent versions.
