### ISSUE TITLE
Custom buttons color doesn't work anymore

### ISSUE THREAD

**Issue by Lukasss93** [MGraefe/RP-Soundboard#43]
Hi, the custom buttons color doesn't work anymore after upgrading TeamSpeak client to 3.1.5 version.

Short video here: http://sharex.lucapatera.it/uploads/2017-07-20_23-14-26.mp4

**Comment by Lukasss93** [comment]
fixed with latest version. <3

**Comment by MGraefe** [comment]
Sometimes I'm quick ;) Had 3.1.5 beta for a while on my second pc but didn't spot the button color not working cause I don't use that feature that much.
