### ISSUE TITLE
Sounds will not play

### ISSUE THREAD

**Issue by 31B442SV5** [MGraefe/RP-Soundboard#44]
After the latest TS update (3.1.5) (7/20/17).  Sounds will not play and any more.   They play in the preview but will not play off the main board.

Any ideas?  I would hate to delete the whole board and start over again.

**Comment by MGraefe** [comment]
Cannot reproduce that - works fine here on TS 3.1.5. Are you sure you haven't enabled "mute on my client" by accident?

**Comment by 31B442SV5** [comment]
I updated the sound board today and it still won't work.  I tried to add new sounds to the existing board and they also do not play.  Mute box is not checked.

**Comment by T4LLY-0** [comment]
Same issue (not playing on recent update) I even un-installed, also removed from the roaming folder and re-installed again. Preview works. 
Also noted it will not detect connected to the TS server. But I've not re-produced the event every time.

**Comment by 31B442SV5** [comment]
I also have the problem of not connecting to the TS server.  I uninstalled the sound board and reinstalled and it is still not working.  Some times if I mash a button six or seven times it will play a sound.

**Comment by MGraefe** [comment]
Could you please install the previous version and tell me if the problem also exists there. Just install it over the old soundboard and decline the update: http://www.mediafire.com/file/cohf0dz7z5rbxp7/rp_soundboard_1678.ts3_plugin

**Comment by T4LLY-0** [comment]
Installed and the sound issue still persists. Soundboard now (for now) becomes active on joining a server, which I found it not doing before.

**Comment by T4LLY-0** [comment]
After just re-installing TS-3 and the soundboard we have a working model. I don't know what the issue was but it has cleared what ever it was. 
This is a fun thing to have, so was keen on getting it working again. Awesome work. Thanks.

**Comment by 31B442SV5** [comment]
T4LLY-0 Did you reinstall the old version of TS or the current version?

**Comment by MGraefe** [comment]
I'd really like to know what was causing this...seems weird. Did your reinstallation orgy erase the soundboard config? So that you have a pristine soundboard without any sounds set?

**Comment by 31B442SV5** [comment]
I had to reinstall TS and the plug-in that you provided. I did not install
the update and everything is working. :)  Unfortunately, I now have to
recreate my soundboard. :(

**Comment by 31B442SV5** [comment]
Update.  I was able to import my old soundboard config and it worked for
one sound.  I went to Config 2 and now config won't work again.

**Comment by T4LLY-0** [comment]
Installed the older version, then the new one. Something must've just sorted itself. But on installing the old version, it still didn't work.

**Comment by 31B442SV5** [comment]
I think it has something to do with the config buttons. I reinstalled TS
and got it to work, but when I clicked config 2 to try my buttons on that
board, it broke the board. I had to uninstall and then reinstall TS to get
it to work again.

I haven't touched my Config 2 this try fearing it will break the board.

**Comment by tgodtaylor** [comment]
After reinstalling my Audio Device driver the soundboard doesn't work even after reinstallation.
The Device driver needs to have the same name!
