### ISSUE TITLE
[Feature Request] Skipping Sound

### ISSUE THREAD

**Issue by martinamama** [MGraefe/RP-Soundboard#47]
For example if i add a sound file which has multiple songs in it, I want to skip some time, because maybe i dont want to hear song 3 out of the 10 songs that are in that one file. So I want to fast forward my mp3 file to a specific point.

**Comment by MGraefe** [comment]
If you just want to get rid of the start or the end of a sound you could maybe use the cropping feature. Leaving out specific portions in the middle of a sound file is a bit too specific and complicated IMHO.
