### ISSUE TITLE
Binding shortcuts

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [MGraefe/RP-Soundboard#5]
When pressing escape, it doesn't cancel the shortcut, it takes the escape key as shortcut

**Comment by MGraefe** [comment]
There is nothing that I can do about that, the Window that appears when you set a shortcut is actually done by Teamspeak itself.

**Comment by ZatsuneNoMokou** [comment]
So it's an issue of Teamspeak?

**Comment by MGraefe** [comment]
Yes.
