### ISSUE TITLE
[Feature Request] Chat command to play sounds

### ISSUE THREAD

**Issue by DosMike** [MGraefe/RP-Soundboard#52]
Would be nice if there was a chat command to quickly play sounds like this:  
`/rpsnd <Configuration> <Button Label | Button Number>`  
or  
`/rpsnd <Button Label | Button Number>` (using active configuration)  
(and maybe `/rpsnd` to just open the soundboard maybe)  
I know there are hotkeys, but I can't hotkey every sound and I like commands :)

**Comment by DosMike** [comment]
I think something like this should work - can't test it right now though
```
/** play button by name or index(strtol), return 0 on success */
int sb_playButtonEx(const char* button) {
	long arg1 = strtol( button, NULL, 10 ); 
	
	if ((NULL != configDialog) && (configDialog->hotkeysEnabled())) {
		if (arg1 <= 0) {
			//TODO search by name, too lazy right now
		} else {
			const SoundInfo *sound = configModel->getSoundInfo(btn);
			if (sound) {
				sb_playFile(*sound);
			} else return 1;
		}
	}
	return 0;
}

/** return 0 if the command was handled, 1 otherwise */
int sb_parseCommand( char** args, int argc ) {
	if( argc >= 3 ) 
		return 1;
	else if( argc == 0 ) {
		sb_openDialog();
	} else if( argc == 1 ) {
		long arg1 = strtol( args[0], NULL, 10 ); 
		if( strcmp( args[0], "stop" ) )
			sb_stopPlayback();
		else if( sb_playButtonEx( args[0] ) != 0 )
			ts3lib.printMessageToCurrentTab("No such button found");
	} else if( argc == 2 ) {
		long arg0 = strtol( args[0], NULL, 10 );
		int pconfig = configModel->getConfiguration(); //TODO ConfigModel::getConfiguration() { return m_activeConfig; }
		if ( arg0 < 1 || arg0 > 4 ) 
			ts3lib.printMessageToCurrentTab("Invalid configuration number");
		configModel->setConfiguration((int)arg0); //switch to specified configuration
		if( sb_playButtonEx( args[0] ) != 0 )
			ts3lib.printMessageToCurrentTab("No such button found");
		configModel->setConfiguration(pconfig); //return to previous configuration
		
	}
	return 0;
}
int ts3plugin_processCommand(uint64 serverConnectionHandlerID, const char* command) {
	char* args[3]; // <[conf] <snd>|<stop>> -> max 2, 3+ == error
	char* token; //last strtok result
	int argc=0; //number of arguments
	token = strtok( command, " " );
	while( token != NULL && argc < 3) { //read a token
		args[ argc++ ] = token; //append token, increase arg counter
		token = strtok( NULL, " " ); //try to read next token
	}
	
	//convert string to lower (if you know a lib you can use it
	for( int a=0; a<argc; a++ ) {
		char* b = args[ argc ];
		for (; *b != 0; b++)
			//assuming ascii encoding, turning on the 6th bit (value equals space) will convert it to lower case
			if ( *b >= 'A' && *b <= 'Z' )
				*b |= ' '; // tuning on 6th bit, converting upper case letters to lower case (see ascii table)
	}
	
	return sb_parseCommand( args, argc );
}
```

**Comment by MGraefe** [comment]
Nice work. Could you put this into a pull request? Also you have to specify the command by implementing this function: 

    const char* ts3plugin_commandKeyword() 
    {
        return "cmdtest";
    }

While you are at it you could also adjust the paranthesis style and I would be happy to accept it. If you are unsure if it works or even compiles - in case you didn't go through the hassle of setting up a working compile environment - I could also test the code for you, just submit it ;)

**Comment by DosMike** [comment]
You already implemented that with `ts3sb` in your [plugin.cpp](https://github.com/MGraefe/RP-Soundboard/blob/master/src/plugin.cpp#L156) as far as I've seen.
I'll sort everything and make a PR soon-ish (I actually wrote that in the comment editor Kappa)

**Comment by MGraefe** [comment]
Oh okay, I missed that it was already implemented. By the way you can use QString's toLower() function, your function is a bit...hacky ;) Same goes for the string comparison stuff, QString simplifies most things a lot.

**Comment by DosMike** [comment]
Sorry, I'm not that familiar with Qt - I know it's making a lot of stuff easier and I should take a look closer at some point, but today is not that day ^.^
Do you want me to PR into master? you don't seem to have a dev branch

**Comment by MGraefe** [comment]
Yeah, master is fine.

**Comment by MGraefe** [comment]
Accepted the merge, for comments look there. I don't want to push out an update for all users as long as the command syntax is not fixed somehow, there are a few things I'd like to change. Also, I don't like to push out an update just for this one feature that honestly not many people will ever use.
Should I send you the updated binaries so you don't have to build it yourself?

**Comment by MGraefe** [comment]
Here you go: http://www.mediafire.com/file/05hncl21c3hk4q2/rp_soundboard_1738.ts3_plugin

**Comment by DosMike** [comment]
Yea, just this one feature seems a bit lacking for a whole update. And even though it surely can be improved it's a base to build upon.
Also thank you very much for compiling it :)
