### ISSUE TITLE
how to use RP in linux?

### ISSUE THREAD

**Issue by sarih** [MGraefe/RP-Soundboard#55]
hi
you say "Currently only Windows is supported."
this mean i cant use it in linux

**Comment by olback** [comment]
What's the issue here?
If you're on Arch, there is a rp-soundboard package (unofficial (i think?))

**Comment by sarih** [comment]
@olback i cant find version of RP-S for linux debian

**Comment by olback** [comment]
@sarih That's because you're not on Arch. Also, the download page clearly says it's Windows Only. And yes, that means that you cannot use RP Soundboard on Debian right now.

**Comment by MGraefe** [comment]
Calm down. There isn't a binar release for any Linux at the moment but nothing stops you compiling the .pro file for Linux yourself. It might require some modification as it isn't updated regulary. Also you have to install libav-dev or libffmpeg-dev depending on the system as well as Qt 5.6.

**Comment by bertalanimre** [comment]
Just qurious: Can't I just implement the .ts3_plugin file into a downloaded Linux version of TS?

**Comment by mrbesen** [comment]
no, because you need to compile the sources into a difrent format (windows: dll, linux: so)
