### ISSUE TITLE
Continuous activation / Permanent whisper

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [MGraefe/RP-Soundboard#6]
I don't know the exact origin of the bug, but sometimes, we get "blocked" in "talking" state, I think it could be linked to your plugin

**Comment by ZatsuneNoMokou** [comment]
I think that your plugin switch to continuous activation and sometimes it doesn't detect the end correctly and stay in continuous activation

**Comment by MGraefe** [comment]
fixed
