### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Rushgarroth** [MGraefe/RP-Soundboard#60]
Is it possible to make the UI around the buttons darker, lets say black so if i have the soundboard open on my second monitor it isnt so bright?
Would be great if we could change the Background from the general UI also like the buttons. Or a simple inverted Theme.

**Comment by olback** [comment]
You can theme TS3with e.g. Simplex, this will also affect RP but it won't look as intended. Black item disappear with dark themes, they're still there but you can't see them.

I personally use Simplex and just click in the general area of the things I can't see and usually hit them.
But it would be nice to have this feature natively in RP.

[Simplex](https://forum.teamspeak.com/threads/107745-RELEASE-SIMPLEX-Designed-to-be-simple-Custom-Icons-and-Style!)
[TS3 Themes](https://forum.teamspeak.com/forums/112-Skins-Icon-amp-Sound-Packs)
