### ISSUE TITLE
Can´t start playing sounds with hotkeys

### ISSUE THREAD

**Issue by jumpY21** [MGraefe/RP-Soundboard#61]
I am able to start sounds when i click on the button.
But unfortunately, when i assign a hotkey for a specific button and press the hotkey, the sound won´t start.

![chrome_2018-01-02_14-49-59](https://user-images.githubusercontent.com/35033656/34485729-5a708bea-efcc-11e7-91ff-01d88a3ad6b6.png)

**Comment by scitbor** [comment]
same here!

**Comment by MGraefe** [comment]
Duplicate of #48
