### ISSUE TITLE
Virtual audio device, music wont play (LINUX DEBIAN)

### ISSUE THREAD

**Issue by eskejpo** [MGraefe/RP-Soundboard#67]
Hello, I wanted to use core of your plugin as part of my project, well so i decided to download it. I compiled it with no probs, plugin loaded but it wont play audio if audio device is virtually created (I guess this is the problem).

```
//init
ts3Functions.registerCustomDevice("customWaveDeviceId", "DisplayName", 44100, 2, 44100, 2);

//onConnectStatusChangeEvent
if ((error = ts3Functions.openCaptureDevice(serverConnectionHandlerID, "custom", "customWaveDeviceId")) != ERROR_ok) {
	printf("%u Error opening capture device\n", error);
}
```

Code i use to create audio device

EDIT: Default audio devices works, but i need to use virtually created one for specific reasons

**Comment by MGraefe** [comment]
This is very specific for your use case, my guess is that this is an issue with Teamspeak itself, especially the Linux version isn't that well maintained I would say. Will mark this as 'wontfix' but leave it open in case any fellow plugin developer can help you.

**Comment by eskejpo** [comment]
Well, first of all thanks for your answer and I also understand your decision. Well, I have one final favor from you. Could you point me to file/line where the fun about devices is? I will do some research. Its hard to mess in code you did not write, using libraries you have never seen. Thanks.

**Comment by MGraefe** [comment]
The plugin uses no (virtual) audio devides but modifies the microphone and speaker audio stream PCM samples directly via the `ts3plugin_onEditMixedPlaybackVoiceDataEvent` and `ts3plugin_onEditCapturedVoiceDataEvent` callbacks. It uses ffmpeg to decode audio and resample that to 48kHz (in inputfileffmpeg.cpp), which is the sample frequency of Teamspeaks Audio channels and then literally adds that onto the data received by the mentioned callbacks. This happens in samples.cpp. I know my filenames for this project are all over the place, I apologize.

**Comment by eskejpo** [comment]
Well, ts3plugin_onEditCapturedVoiceDataEven is not being triggered if custom audio device is being used. Possible solution would be to rewrite it using ts3Functions.processCustomCaptureData. Well, maybe if i have time and mood i will try to do it. 

Thats all from me, thanks. (If anyone reading this has any ideas, dm or respond here? Yay)
