### ISSUE TITLE
Add Hotkey to ini file

### ISSUE THREAD

**Issue by kleinpoe** [MGraefe/RP-Soundboard#70]
Currently the hotkey is not included in the .ini file. I made a matlab script to add all of my sound files (in a folder) to your soundboard, but I cannot automate the hotkey binding. Here is the script if someone is interested https://1drv.ms/u/s!AsbhbBKCtv4QmsMKFHxdGbGARa1ntQ
Thanks for your work, it's great!

**Comment by MGraefe** [comment]
The hotkeys are stored by Teamspeak itself in a sqlite database, that's why they aren't in the INI file. I simply use the hotkey functionality provided by Teamspeak.
