### ISSUE TITLE
[Feature Request] Elgato Stream Deck support

### ISSUE THREAD

**Issue by Sebastian1989101** [MGraefe/RP-Soundboard#72]
After elgato published the SDK for the Stream Deck, it would be very nice if it is getting support from the rp_soundboard plugin. The SDK can be found here: https://developer.elgato.com/documentation/

**Comment by MGraefe** [comment]
I believe that you can emulate key strokes with the Stream Deck, so you can set these as hotkeys in Soundboard and you are good to go. Adding dedicated support for a niche device seems to be a bit out of focus.
