### ISSUE TITLE
Soundboard doesnt update or install at all

### ISSUE THREAD

**Issue by h9lz4** [MGraefe/RP-Soundboard#74]
hi there.
PR soundboard wouldnt let me update so i thought a reinstall might be the solution ... deinstalled and tryed to reinstall and now this doesnt work either. please help! also tried as administrator

RP version: 1.4.0.1790
teamspeak version: 3.2.3
windows 10

![z0hyneb](https://user-images.githubusercontent.com/47333671/52230722-6b409980-28b8-11e9-8e32-f58c5060fbbb.png)

**Comment by Bluscream** [comment]
Close teamspeak while installing
