### ISSUE TITLE
[Feature Request] Load specific configuration on startup

### ISSUE THREAD

**Issue by ezsnipes** [MGraefe/RP-Soundboard#77]
Hello,

I'd like to submit a feature request:
When using multiple configurations it would be nice to have an option/setting to specify which configuration should be loaded on startup. This is pretty handy in cases (like mine) where your "main" configuration (the one you commonly use) ain't on the first slot.

Any feedback about this feature request is appreciated.

Best Regards

**Comment by MGraefe** [comment]
Doesn't it stay on the previously selected configuration after restart?
