### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by Bixilon** [MGraefe/RP-Soundboard#78]
This isn't actually an issue But: Can you upload to myTeamSpeak Linux binaries? This would be helpful.

Or can you provide an download Link in the ReadMe?

Thanks

**Comment by MGraefe** [comment]
A linux version is currently not maintained, sorry.

**Comment by Bixilon** [comment]
Hmm. That are bad news. Is it planned?





Am 30. März 2019 10:09:43 MEZ schrieb "Marius Gräfe" <notifications@github.com>:
>A linux version is currently not maintained, sorry.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MGraefe/RP-Soundboard/issues/78#issuecomment-478223815

-- 
Von bixilon.de gesendet
