### ISSUE TITLE
Upgrade API to v23

### ISSUE THREAD

**Issue by TheKeymaster** [MGraefe/RP-Soundboard#79]
Teamspeak introduced API v23. At the moment the Plugin is unusable when using the newer version.

**Comment by drburtchett** [comment]
Not sure when this might get updated, but it's an easy fix. I didn't notice any changes between the v22 and v23 functions that RP-Soundboard calls. Simply change "src/plugin.cpp" class variable "PLUGIN_API_VERSION" to 23. Rebuild project from source (with qmake) and move your newly built "rp_soundboard" library binary to the "${T3_DIR}\config\plugins" directory. Worked for me using Windows 10 x64 and Visual Studio C++ community. Make sure you have the QT5+ framework installed.

Note: I upgraded the vcxproj file to use vs2019--which was kind of a pain. I suggest novice users who don't want to spend the day debugging code to use vs2015.

Hope this helps.

**Comment by TheKeymaster** [comment]
I am struggling very much with building this x). I never coded in C++ and therefore I do not know how to build stuff with qmake. I tried reading myself in, but I did not manage to do it in a short time. Could you provide the plugin file itself? Creating a PR for updating the plugin version is not that hard if nothing has changed regarding the API, since it's only a version bump. That is/was no problem.

Thanks!

**Comment by MGraefe** [comment]
> Not sure when this might get updated, but it's an easy fix. 
I will do the upgrade next week. Maybe I can also include some other minor quality of life improvements in this update.

> Worked for me using Windows 10 x64 and Visual Studio C++ community.
Thanks for your work!

> Make sure you have the QT5+ framework installed.
I will need to upgrade to QT 5.12 when Teamspeak 3.3 is released.

> Note to Win Users: I created a fork for VS 2019 community users.
VS 2019 should support reading 2015 project files, it should be backwards compatible. Just choose 'no' when it asks you if you want to upgrade to new compiler versions.
Teamspeak3 is using VS 2015, so it already comes with the proper redistributable and links to the VS2015 version of Qt.

I hope I can roll out an update to the plugin before the update to Teamspeak 3.3 rolls out. For this the built of RP Sounboard for the 'new' Qt and API version needs to be backwards compatible with Teamspeak 3.2 which is worrying me a bit. I want to prevent that users need to manually install RP SB again.

**Comment by MGraefe** [comment]
Done, build for new version can be downloaded at https://forum.teamspeak.com/threads/125318-RELEASE-RP-Soundboard

Cross compatibility between Teamspeak 3.2 and 3.3 doesn't work, so there's no way I can automatically push an update using the built in updater without breaking stuff. So you will have to manually re-download if you didn't install the addon via myTeamspeak.

I also upgraded the project files to VS2017 as this is what the Teamspeak devs are using (and it's the version of Qt they are linking to).

**Comment by dburtchett** [comment]
> > Worked for me using Windows 10 x64 and Visual Studio C++ community.
> 
> Thanks for your work!

Thanks. I didn't do much, but I appreciate the work you and the devs have done on this project and wanted to see if I could give you and your team some breathing room to make the necessary changes. My squad and I love this plug-in for TS3.

> > Note to Win Users: I created a fork for VS 2019 community users.
> 
> VS 2019 should support reading 2015 project files, it should be backwards compatible. Just choose 'no' when it asks you if you want to upgrade to new compiler versions. You'll have to have the VS2015 compilers installed of course.
> Teamspeak3 is using VS 2015, so it already comes with the proper redistributable and links to the VS2015 version of Qt.

Sorry, that was my [poor] attempt at trying to save time of having to download another module (e.g., VS 2015 compiler), but I probably ended up spending more time making tweaks to the environment config than if I just downloaded and linked the 2015 compiler. Thanks for the info that will save me from being out-of-sync with TS3/QT libraries.

Also, I'll revert my fork to use VS 2017 to be compliant with you and your team, just in case I might make some custom features in the future.

**Comment by dburtchett** [comment]
> Done, build for new version can be downloaded at https://forum.teamspeak.com/threads/125318-RELEASE-RP-Soundboard

I just wanted to thank you and your team again. You and your team have done a great job on this plugin and the support updates too. Kudos, all.

> Cross compatibility between Teamspeak 3.2 and 3.3 doesn't work, so there's no way I can automatically push an update using the built in updater without breaking stuff. So you will have to manually re-download if you didn't install the addon via myTeamspeak.

I think that is fair.
