### ISSUE TITLE
Issues Building

### ISSUE THREAD

**Issue by Claush17** [MGraefe/RP-Soundboard#80]
I am using Visual Studio Community 2017, I build as I exported it, and is getting an error.

Error	MSB6006	"cmd.exe" exited with code 3.	rp_soundboard	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	209

**Comment by MGraefe** [comment]
Do you have python installed?
