### ISSUE TITLE
Add a (free) License to the project

### ISSUE THREAD

**Issue by tassadarius** [MGraefe/RP-Soundboard#89]
Greetings,
first things first I really enjoy the sound board.
I was compiling it for Linux on the weekend and there are some who request the Linux binaries.

Have you considered adding a free software license to the project? So people (maybe me) could build, check and provide the Linux binaries.

If you do not want that you could still add a license file and explicitly stating that the software belongs to you and may not be freely distributed.

Would be cool, have a nice day.

**Comment by MGraefe** [comment]
Hi, first of all thanks for doing a Linux build. In case you fixed some configuration files I would be happy to accept a Pull Request with the stuff you did.

As with the license: What license would you suggest? I think it would have to be compatible with LGPL since that's the license ffmpeg uses.

I would be more than happy to put my actual source code under an open source license. But as far as the binaries go, I would like to remain in charge of supplying (and building) binaries for RP Soundboard. It's a software a lot of users download as binary and I would like to exactly know what gets compiled into them before I make something available for download.

Now that I have some free time on my hands (who doesn't) I am planning to add some quality of life features and update other stuff anyway. I would be happy to build a linux version and officially make it available as well.

**Comment by tassadarius** [comment]
Hey, that's great.

**Compatibility to FFmpeg's LGPL 2.1**
You do not need to worry about compatibility to LGPL. It was written for libraries which may be used in any software, even proprietary, as long as you are able to change FFmpeg. This is totally possible since you provide the source code. (see Section 5 and 6 in the [LGPL](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html) for specific wording).

----

Providing the binaries yourself is completely fine and I understand your considerations. :+1:
My built went smooth, I don't think I had to change anything. I used following setup:

| Property | Version |
|------------|----------|
| Qt | 5.12.7 |
| Teamspeak3 | 3.5.1 |
| Distro | Manjaro (latest patches 05.04.2020) |
| Compiler | g++ (Arch Linux 9.3.0-1) 9.3. |

----

**Suggested Licenses**
Since it is up to you I will suggest some and explain a little bit. I don't think you have to considerate things like patents so it should not be that great of a deal:
 * `GPL (copyleft):` The GNU General Public License is a common copyleft license. It not only guarantees the users are allowed to run, share and modify the software. It goes a step further and requires that every further modification / forks / derivatives must be licensed under the same or equal license. This way you can make sure that the work stays Free Software.
* `Apache 2 (permissive):` Quite common permissive license. I do not know that much about it. Permissive means it allows more than the copyleft licenses. For example a derivative work (further versions or modifications) may have a different or even proprietary license).
* `MIT License (permissive):` Very short and simple, also permissive.
*  `4-clause BSD (permissive, advertising clause)`: This one is quite similar to MIT, except it has the advertising clause. That means any derivative work must mention the original source (you).
* `3-clause and 2-clause BSD (permissive)`: Similar to 4-clause BSD without the advertising clause.

The free software foundation has some recommendations (although they always suggest the GPL :D)
https://www.gnu.org/licenses/license-recommendations.html

As well as a List of Open Source / Free software licenses:
https://www.gnu.org/licenses/license-list.html#SoftwareLicenses

**Recommended**

* If you want it to be free software and stay free software I would choose the `GPL` in version 2 or 3. Basically a no-brainer. GPL does exactly that and is widely used.
* If you want it to be free software, but maybe want to make it proprietary in any version I would choose the `MIT`. It's permissive short and widely used.
* If you want it to be free software and want to stay associated with it I would choose the `4-clause BSD`. It has the advertising clause.

**What do you have to do**
It should suffice to put a LICENSE file in the root directory of the GitHub project, as well as ship the LICENSE file with the binaries. (Since the .plugin files are zip archives this should be no problem).
GitHub even provides a button where you can choose from the most common ones.

Many times you see that a license info is at the head of every file. This is recommended practice but AFAIK not required by any of the listed licenses. 

**NOTE:** I am not a lawyer or software license expert. That should just be an overview and there may be some mistakes or subtleties I missed here and there.

**Comment by MGraefe** [comment]
Wow thanks for the comprehensive overview! In Österreich ist auch reichlich Zeit vorhanden wie ich sehe :D No offense ;)

I have 4 day weekends at the moment so I will start with some things at the end of the week.

Regarding the license: I don't really care about copyleft but would like to stay associated with my source code and would like to make sure nobody can release software under the name 'RP Soundoard'. Will have a look at the options.

Regarding the build: What is your expertise with sharing binary linux libraries that link against system libraries like ffmpeg/libav*. How big are the chances that the user has a lib installed that is incompatible with the one that I linked against when I built the linux binary? I would imagine the safe bet is to statically link against ffmpeg like in the windows build, that's a bit of work though.

**Comment by MGraefe** [comment]
At second thought: fuck it I will just put it under MIT. I benefited so much from MIT licensed software (npm packages) and other free software, time to give something back :D

**Comment by tassadarius** [comment]
@Building on Linux:
I would just add it in the README as external dependency.

The required libs should be in the Debian [package](https://packages.debian.org/stable/ffmpeg) of ffmpeg (`sudo apt-get install ffmpeg`). I have not tested it but also in the Arch [package](https://www.archlinux.org/packages/extra/x86_64/ffmpeg/) (`sudo pacman -Sy ffmpeg`). For  As it should get statically linked that should be enough.

I can make a PR for de README explaining the build process on Linux and test it in a virtual machine.

**Comment by MGraefe** [comment]
I am currently migrating the whole mess that is the current build procedure of this addon to CMake, you might want to check out the branch cmake-build-system. I also plan to statically link a custom build of ffmpeg together with the addon as it's just less error prone, especially for people that just want to do a "one click" installation via myTeamspeak.

Thanks for considering adding build information to the readme, just hold back a little while until I'm done with the migration to CMake.

**Comment by MGraefe** [comment]
Merged the cmake build system branch. It consequently removes the old project file folders (vs2017, qt-mac and qt-linux).

I also released an official version for Linux x64: https://github.com/MGraefe/RP-Soundboard/releases/tag/1.4.1.1817_linux

**Comment by tassadarius** [comment]
Now has a free software license. Great thanks!
