### ISSUE TITLE
Install on linux

### ISSUE THREAD

**Issue by TheSadBoyy** [MGraefe/RP-Soundboard#90]
Hello, I would like to know if it was possible to install it on Ubuntu 19.10 and how to install it precisely, could someone help me?

**Comment by MGraefe** [comment]
I am currently working on an official build for Linux, just wait a few days :)

**Comment by Bixilon** [comment]
a small b u m p

**Comment by MGraefe** [comment]
https://github.com/MGraefe/RP-Soundboard/releases/tag/1.4.1.1826_linux

**Comment by Bixilon** [comment]
Thank you:)

(just ignore my comment :D, only looked into this issue, not into the releases)

**Comment by MGraefe** [comment]
No problem, I should've noticed you. I appreciate any feedback regarding the linux build.

**Comment by Bixilon** [comment]
Looks pretty stable. just tried it. I will open an issue, if i find bugs.
