### ISSUE TITLE
.lock/lock.rmlock 

### ISSUE THREAD

**Issue by RedCome** [MGraefe/RP-Soundboard#91]
hello guys, I apologize for the bad english. My problem is the team peak creates a lot of files see link http://prntscr.com/rxsrh4. Have already reinstalled! Can somebody help me

hallo Leute, Mein Problem ist das Teamspeak jede menge Datein erstellt sehe Link http://prntscr.com/rxsrh4 5. Hab auch schon Neuinstalliert! Kann mir wer helfen. jedes mal wenn ich ts neustarte kommen 1-3 datein dazu und irgendwann braucht es ewig lange um starten!

**Comment by MGraefe** [comment]
Hi, das hat nichts mit meinem Addon zu tun. Frag am besten mal im offiziellen Teamspeak Forum nach, da können auch einige deutsch: https://community.teamspeak.com/
